FROM postgres:16

RUN apt-get update && apt-get install -y postgresql-server-dev-16 build-essential git && \
    git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git /pgvector && \
    cd /pgvector && make && make install && \
    cd / && rm -rf /pgvector && \
    apt-get remove -y build-essential git && apt-get autoremove -y && apt-get clean

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432